### ISSUE TITLE
Avro schema serialization

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#1]
https://avro.apache.org/docs/current/

**Comment by gmr** [comment]
Interesting project! I'm currently evaluating the spec for suitability of use.

I noticed this issue and wanted to anecdotally let you know that at [WORK] we use Avro datums for our AMQP message bodies and schemas for the marshaling and demarshaling of data. I'm curious about what the intent of this issue is? Would it be to allow for Avro schema style definitions of message payloads?

**Comment by fmvilas** [comment]
Hey @gmr! Thanks for your words. To be fair, that was the first "issue" I created before creating AsyncAPI and was there as a way to not forget about it. I've been thinking about how to integrate Avro and Protobuf with AsyncAPI but doesn't seem an easy task. If you come up with a solution I'll be glad to consider it 👍
