### ISSUE TITLE
Server Variable object different property requirements to OAS

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/asyncapi#103]
https://github.com/asyncapi/asyncapi/blob/master/README.md#fixed-fields-5

> At least one of the fields MUST be provided.

It seems odd you can get around the requirement for *either* `enum` or `default` (which itself is different from OAS) by providing a `description`, even an empty one.

Could you clarify this rule and difference for me?

**Comment by fmvilas** [comment]
Yeah, say for instance you have a URL like the following one:

```
https://myserver.com/users/${userId}/connect
```

Here `userId` can't have an enum nor a default, but it can always have a description.

What I agree is weird in this case is that you can just provide a empty description and would be valid. We probably need to have a schema or subset of a schema object there and make it mandatory.

**Comment by fmvilas** [comment]
@MikeRalphson I'm trying to tackle this issue but I'm not sure we should do something here. A server variable is optional and if someone wants to just pass an empty description is actually nonsense because they can just avoid adding the variable in first place, right?

##### Examples of empty variable definition

Passing an empty object:

```yaml
servers:
  - url: https://stream.gitter.im/v1/rooms/{roomId}/chatMessages
    variables:
      roomId: {}
```

Avoiding the definition:

```yaml
servers:
  - url: https://stream.gitter.im/v1/rooms/{roomId}/chatMessages
```
