### ISSUE TITLE
v2 spec examples should show one level higher for context

### ISSUE THREAD

**Issue by jhigginbotham** [asyncapi/asyncapi#194]
Examples should prefix the section they are highlighting for context. Currently, I have to pull up an example to understand where an example would fit into the definition file while learning about v2.

e.g. channels examples start with the channel name. Show one level up, e.g. 'channels' so that there is some context on where it fits and copy-and-pasters have better success in understanding where it fits

e.g. $ref examples show no context, so the example is too trivial for understanding how it would look in a definition file for a schema ref

**Comment by fmvilas** [comment]
While I understand the concern, I'm not sure this should be the way to do it, because we're putting examples of an object "X". It may also lead to confusion making you think the, for instance, "channels" must be part of the object.

If people want to learn AsyncAPI they should go to the documentation and tutorials. The specification should be just for reference.
