### ISSUE TITLE
[2.0.0 REVIEW] Specific protocol for publish/subscribe

### ISSUE THREAD

**Issue by olvlvl** [asyncapi/asyncapi#217]
# AsyncAPI Review Document

|Project name|Reviewers|Company|Spec version|
|------------|---------|-------|------------|
|-|Olivier Laviale|HelloFresh|v2.0.0|

## Our goals with this project are to:
  1. Document our RabbitMQ bindings and link publishers and subscribers
  2. Draw a graph of dependencies

## We expect to:
  1. Accurately describe topics, exchanges, queues, schemas

## We found the following challenges or difficulties:

1. _protocolInfo_ is now available in 2.0.0-rc1. It is defined next to `subscribe` and `publish`, and thus assumes they are using the same protocol. If we setup a bridge between RabbiMQ and Kafka how do we define that we subscribe using RabbitMQ and publish using Kafka?

    https://www.asyncapi.com/docs/specifications/2.0.0-rc1/#a-name-channelitemobject-a-channel-item-object

2. Still about _protocolInfo_, it's not clear to me what's the best way to describe queues and exchanges. Up until now we've been using extensions such as `x-amqp-exchange` and `x-ampq-queue`. Should we define these in _protocolInfo_? Again we have the same issue with the placement of _protocolInfo_. In our case, we have a service publishing ` orders.cutoff` event and some services subscribe to that event to publish their own `orders.cutoff` event on their own exchange. For instance we have an order-creation service publishing `orders.cutoff` on its own exchange then `menu-addons` service and `recipe-charge` service subscribing to that event and publishing their  `orders.cutoff` on their own exchange. Thus we need a way to specify exchange and queue _inside_ `publish` and `subscribe`. Should we continue using extensions? Seems like a missed opportunity, especially since _protocolInfo_ is free form.

#### We think it can be solved by...

We think it can be solved by moving _protocolInfo_ inside `subscribe` and `publish`.

#### Overall, we think this challenge/difficulty is...
  * [x] A "nice to have".
  * [x] A blocker for us to adopt this version of the spec.
  * [ ] Something that doesn't affect the specification.

---
_AsyncAPI Initiative — (website: [asyncapi.org](https://asyncapi.org), twitter: [@AsyncAPISpec](https://twitter.com/AsyncAPISpec))_

**Comment by fmvilas** [comment]
Hi @olvlvl!

Thanks for the thoughtful review. Let me answer point by point:

1. There's already a `protocolInfo` property on the operation object (i.e., inside publish and subscribe): https://www.asyncapi.com/docs/specifications/2.0.0-rc1/#operationObject. Is this what you are asking for?

2. I know protocolInfo objects are confusing right now. The reason is that it's an unfinished work. The idea is to have a collection of protocolInfo objects in a registry or catalog, so everybody follows the same "rules" and therefore is somehow standardized even being free-form. That would help tooling authors support them. Check what we have so far: https://github.com/asyncapi/extensions-catalog. To clarify: extensions can be specification extensions and protocolInfo objects. We might decide to rename protocolInfo objects to "protocol extensions", as it may make more sense.

It would be amazing if you could help us figure out the shape of the `amqp-0-9-1` and `kafka` protocol extensions, as I can see you're going to use both. Doesn't have to be very formal. If you already have a JSON object that you use that would be enough to start the conversation.

Thank you again for this thoughtful review. It really helps a lot!

**Comment by olvlvl** [comment]
Hi @fmvilas,

Thanks for your message. I'm happy to learn `protocolInfo` is available in the message spec. Can you tell me if the following would be correct? (I left out `/components/schemas/MenuId`).

```
asyncapi: 2.0.0
info:
  title: menus-service
  version: latest

topics:
  menu.activated:
    publish:
      $ref: '#/components/messages/menuActivated'

components:
  messages:
    menuActivated:
      summary: Message sent when a Menu gets activated.
      tags:
        - name: menu
        - name: activate
      payload:
        $ref: '#/components/schemas/MenuId'
      amqp-0-9-1:
        exchange: menus-service
        type: topic
        durable: true
```

```
asyncapi: 2.0.0
info:
  title: recipes-service
  version: latest

topics:
  menu.activated:
    subscribe:
      $ref: '#/components/messages/menuActivated'

components:
  messages:
    menuActivated:
      summary: A menu was activated
      tags:
      - name: menu
      - name: activate
      payload:
        $ref: '#/components/schemas/MenuId'
      amqp-0-9-1:
        exchange: menus-service
        queue: recipes-service.menus_service
        durable: true
        noAck: true
```

We would like to be able to use the `asyncapi.yaml` file as source of truth to setup exchanges and queues, and also build contracts between publishers and subscribers. Being able to accurately describe them without using extensions would help a lot.

**Comment by fmvilas** [comment]
It's almost correct. `amqp-0-9-1` should be inside `protocolInfo` key. Please note this can change soon as the current version is still not definitive.

```yaml
asyncapi: 2.0.0
info:
  title: menus-service
  version: latest

channels:
  menu.activated:
    publish:
      $ref: '#/components/messages/menuActivated'

components:
  messages:
    menuActivated:
      summary: A menu was activated.
      tags:
        - name: menu
        - name: activate
      payload:
        $ref: '#/components/schemas/MenuId'
      protocolInfo:
        amqp-0-9-1:
          exchange: menus-service
          type: topic
          durable: true
```
