### ISSUE TITLE
Deduplication and workflow concerns/questions

### ISSUE THREAD

**Issue by treeder** [asyncapi/asyncapi#233]
I've been building out a demo application that uses AsyncAPI to model it and have some questions/thoughts on the workflow. The [duplication part of publish/subscribing](https://www.asyncapi.com/docs/getting-started/publishing/) and this [proposed way of organizing things](https://medium.com/asyncapi/organizing-your-asyncapi-documents-12bccecd9ced) doesn't feel quite right to me (maybe it's just me?). 

## Demo parts and flow

Taking a few parts of the demo app as an example, we have the following parts and flow: 1) the storefront (browser UI) -> 2) Payment processing -> 3) Fulfillment

User checks out and submits their order. That publishes a message/event to an `orders` topic that the payment processor (PP) is subscribed to. In this scenario, it feels natural that the `orders` channel should be defined by PP and the storefront should get that definition from PP, not from the storefronts own AsyncAPI spec (or to duplicate it there). The same as it would be if it were a REST API (the UI wouldn't redefine the API). The storefront has no say in what broker is used, what the channel is called, nor what format it should be in. 

Then once the payment is processed and successful, PP publishes a message to an `orders_paid` channel for whoever is interested. PP defines the channel used and the data format in its AsyncAPI spec. Interested parties, fulfillment (FF) in this example, can subscribe to that channel. FF has no say in what channel is used or the message format again so why should it duplicate the spec?  It should just use the spec that PP defined. 

## Specs for each App

So how could/should these "apps" organize things?  

**Storefront**

Like any typical UI that uses a bunch of REST APIs, it probably doesn't have any API spec of it's own, sync or async. 

**Payment Processing**

This would have specs (REST and Async) that define its external interfaces. In this example, it would have the `orders` channel spec showing what it expects as its input and the `orders_paid` channel as its output. 

**Fulfillment**

Fulfillment is interested in the `orders_paid` channel defined by payment processing. Defining the fact that it subscribes to the `orders_paid` channel that PP defined seems out of place. Just like it wouldn't define the other Rest APIs it it uses in its Swagger/OpenAPI/RAML spec. 

### Should specs include channels from other apps that it's using?

I understand that in some cases you might want to define what your app _uses_ for use in other systems, but I don't believe it should be mixed in with the API spec that it's _exposing_. Again, in the same way you wouldn't do this in your Swagger/OpenAPI/RAML spec for your REST APIs. 

Perhaps there should be a separate file that defines what an app _uses_ for tools that require it?  With a list of links to channels in other specs.

### If the answer above is yes, then how about Shared Channels?

Much like you can share message formats, could we just share the entire channel to reduce all the duplication?

Perhaps flip the channel and the publish/subscribe name so it could support links, eg:

```yaml
channels:
  subscribe:
    hello:
  # or link to another docs channel:
  subscribe:
    $ref: 'https://helloworldapp.com/asyncapi.yaml#/channels/goodbye'
```

**Comment by fmvilas** [comment]
I understand the pain but I can't really find an alternative solution that will work for everyone. This has been discussed in one of our SIG/public meetings. We agree there should be a way to share channel definitions so you don't repeat yourself all the time. A possible solution would be to do something like [RAML libraries](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#libraries) and use traits. However, I still don't know how to avoid writing the name of the channel everywhere it's used. The example you proposed it's not valid YAML nor JSON and if we merge everything into `publish` and `subscribe` keys we end up with the same problem. Example:

```yaml
channels:
  subscribe
    hello: # You still have to define channel names.
      ...
    goodbye: # You still have to define channel names.
      $ref: 'https://helloworldapp.com/asyncapi.yaml#/channels/goodbye'
```
Or following your second suggestion:

```yaml
channels:
  subscribe
    $ref: 'https://helloworldapp.com/asyncapi.yaml#/channels/goodbye' # What if I want to have a channel called `$ref`? Even if we make an exception, what happens to the `hello` channel below?
    hello:
      ...
```

A possible solution is using traits:

```yaml
channels:
  hello:
    subscribe:
      ... # Definitions for this specific hello/subscribe operation.
    traits:
      - $ref: 'https://helloworldapp.com/asyncapi.yaml#/traits/channel-hello' # channel "hello" commons
```

But this one will need of `traits` support at channel level which I think it's great idea and don't know why we missed that :)

Hope this helps clarify the problem. I'm happy if you come up with better solutions but I can't think of anything better than this right now.

**Comment by treeder** [comment]
> The example you proposed it's not valid YAML nor JSON

It's just pseudo code to express the idea. :)

Well one solution is not having the channels you "use" in your spec at all, only the channels you want to expose as suggested in "Should specs include channels from other apps that it's using?". This would eliminate the need for sharing channels and is more what you'd expect when defining an API. A REST API spec using OpenAPI/RAML doesn't also define the other APIs it uses behind the scenes. For instance if I have an API that uses the Slack API behind the scenes, I don't include the Slack API's in my API spec.

Thoughts on that part before getting into sharing channels?  I'm sure this probably came up in your conversations before, but would be good to know what the thought process was around this.

**Comment by fmvilas** [comment]
Unlike in the request/response paradigm (OpenAPI), in event-driven architectures, you may find many-to-many relationships, meaning that many different actors/services may publish the same type of message to the same channel, and many actors/services may consume these type of messages from these channels. A common example is the following:

1. You have a monolith serving your browser application. When someone signs up, the frontend calls the monolith REST API (e.g. POST /users) and this one publishes an `user/signedup` event to the broker.
2. Then, your company asks you to create a smartphone app that should be able to sign users up too. So the team decides to create a new REST API for mobile because the one on the monolith relies on cookies and other browser mechanisms for sessions. In short, they create a BFF (Backend For Frontend) for each platform.
3. The smartphone calls the mobile BFF REST API to sign a user up, and this one publishes a message to the broker. **Exactly the same kind of message as the one on the first point**. It only has something different **in** the message, for instance a `from` field indicating where the user signed up from, e.g. `"from": "android"`.

So that leaves us with the question "who is the owner of a channel?". When you only have one publisher per channel, one could argue the publisher is the owner. But what happens when this is not true? Who's the owner in this case? All of them, or none. I prefer to think that no application is the owner of any channel. The same way no application is the owner of any type of message. They live on their own, and applications only play the publisher or subscriber role on them (the channels).

You don't have this problem in request/response specs like OpenAPI or RAML because of the nature of these APIs themselves. In an HTTP API, the "channel" (the connection) is created by the application. In event-driven architectures, most of the times you have a broker (RabbitMQ, Kafka, etc.) in charge of creating and maintaining channels. An application simply connects to it but doesn't own it, and therefore you can have those many-to-many relationships.

Does it make sense?

**Comment by treeder** [comment]
Related: https://github.com/asyncapi/asyncapi/issues/223

**Comment by jstoiko** [comment]
@fmvilas: aside from addressing @treeder's concern, wouldn't having traits at the channel level vs operation & message levels simplify things?  while still providing a way to define common operations and messages in there...

**Comment by fmvilas** [comment]
So, you're saying allowing traits at channel level that will span across `channel` > `operation` > `message`? For instance:

```yaml
channels:
  test-channel:
    traits:
      - $ref: '#/components/channelTraits/test'

components:
  channelTraits:
    test:
      subscribe:
        message:
          ...
```

If that's the case, it can raise inconsistencies like merging messages of different schema formats down the channel tree. E.g.:


```yaml
channels:
  test-channel:
    traits:
      - $ref: '#/components/channelTraits/test'
      - $ref: '#/components/channelTraits/testWithAvro'

components:
  channelTraits:
    test:
      subscribe:
        message:
          schemaFormat: 'application/schema+json;version=draft-07'
          ...
    testWithAvro:
      subscribe:
        message:
          schemaFormat: 'application/vnd.apache.avro'
          ...
```

Merging these two is possible because both are JSON structures but how do you really combine JSON Schema and Avro? How would it work on future features like supporting XSD, Protobuf and other non-JSON structures?

In my opinion, traits are not meant to span across the boundaries of a single object. If what we're seeking for is channel reuse, we could simply have this:

```yaml
channels:
  test-channel:
    $ref: 'path/to/test-channel.yaml'
```

Where the file located at `path/to/test-channel.yaml` contains the reusable definition. We could also RAML-like libraries where channels definitions live.

Does it make sense?

**Comment by jstoiko** [comment]
In RAML, traits can be defined at both resource and method levels. The structure of the trait remains the same though. Applying a trait on a resource is a shortcut for applying such trait on all its methods.

To answer your question about merging, I think simply defining the merging rules would address any foreseeable conflicts. In RAML, there is a [set of rules](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#algorithm-of-merging-traits-and-methods). There is no possible conflict as the rules define what takes precedence, either the position in the hierarchy (resource vs method) or in the trait application position itself (position in the `is:` array).

So if we were to define similar rules in AsyncAPI, your example above would be equivalent to:
```yaml
channels:
  test-channel:
    subscribe:
      message:
        schemaFormat: 'application/vnd.apache.avro'
```
since `testWithAvro` would override the `schemaFormat` node of the one defined in the `test` trait.

This is food for thoughts. Maybe it's good as it stands. I think it would be helpful to have a few real-life examples of both Message and Operation traits, as they are currently defined (in `2.0.0-rc1`). The current examples in the spec don't show the value/use-case of each type of traits.

**Comment by fmvilas** [comment]
Agree on having real-life examples. I think we should wait until we see how people want to use traits and what are the requests.

**Comment by treeder** [comment]
BTW, the example app I'm referring to is here: https://github.com/treeder/async-toy-store

**Comment by treeder** [comment]
Another issue came up that is related. Let's say you have the following:

```
channels:
  orders:
    subscribe:
      message:
        $ref: '#/components/messages/order'
  orders_paid:
    publish:
      message:
        $ref: '#/components/messages/order'
        # TODO: Can we add an extra field to a new message type in components?
components:
  messages:
    order:
      payload:
        type: object
        properties:
          id:
            type: string
          amount:
            type: number
          comment:
            type: string
```

Is there a way to add an extra field to an object without duplicating it?  For instance, if it's fulfillment, then it would subscribe to `orders`, ship the product, add the tracking number to the `order` object, then publish it.

**Comment by rmelian** [comment]
@treeder if you share the message payload in an external file then you can reuse it and use allOf to 'extend' it

**Comment by fmvilas** [comment]
No need to have it externally. To extend a schema, use `allOf`:

```yaml
channels:
  orders:
    subscribe:
      message:
        $ref: '#/components/messages/order'
  orders_paid:
    publish:
      message:
        $ref: '#/components/messages/orderWithSomethingElse'
components:
  messages:
    order:
      payload:
        $ref: '#/components/schemas/orderPayload'
    orderWithSomethingElse:
      payload:
        allOf:
          - '#/components/schemas/orderPayload'
          - type: object
            properties:
              somethingElse:
                type: string
  schemas:
    orderPayload:
      type: object
      properties:
        id:
          type: string
        amount:
          type: number
        comment:
          type: string
```
