### ISSUE TITLE
[2.0.0 REVIEW] schemaFormat discussion

### ISSUE THREAD

**Issue by jasonmac01** [asyncapi/asyncapi#246]
In regards to schemaFormat on the [Message](https://www.asyncapi.com/docs/specifications/2.0.0-rc1/#a-name-messageobject-a-message-object) object:

I'm VERY happy to see this attribute. One issue we (AWS API Gateway) had with OpenAPI was a confusion for customers (and ourselves, at times) when interpreting models as an OAS "Schema" versus JSONSchema. Being able to call out a format for the associated schema is great.

One thing that might be nice to add here is a reference to suggested values. I realize the value could be fairly customized. Apparently JSONSchema does not yet have an official type (looks like they're [planning on it](https://github.com/json-schema-org/json-schema-spec/issues/680)). But, the convention would be "application/json+schema;version=X"

At the least, I would think the spec should call out the identifier for the "AsyncApiSchema" type which is the default when the `schemaFormat` is not provided.

**Comment by fmvilas** [comment]
You're right. This needs to be clarified and written down. Just two things:

1. It looks like the folks at JSON Schema are going after `application/schema+json`. Maybe also after `application/schema+yaml`? See https://json-schema.org/latest/json-schema-core.html. However, the draft is expired.
2. The AsyncApiSchema type doesn't really exist. It's actually the OpenApiSchema type and they're advocating for `application/vnd.oai.openapi;version=x` and `application/vnd.oai.openapi+yaml;version=x`. I'm currently investigating the implications of [defaulting to JSON Schema Draft 07](212) instead of the OpenAPI one.

Thanks for pointing out. I'll make sure this gets done before releasing version 2.0.

**Comment by jasonmac01** [comment]
One other note on the schemaFormat property: 

Take for example a  `payload` defined in JSONSchema v4. The schemaFormat is called out properly on the `message.` However, it references a "schema" defined in the "components" section of the document. Unfortunately, the specification mandates that this section is composed of `Schema` objects only. 

Do you think this needs to be adjusted such that the `schemaFormat` can be applied within the individual "components" items as well?

```
  schemaFormat: application/vnd.oai.openapi+yaml;version=4
  payload:
    $ref: '#/components/schemas/Pet'
...
components:
  schemas:
    Pet:
      # This has to be a Schema, but what if it was a JsonSchema4 definition?
```

**Comment by fmvilas** [comment]
`components/schemas` is used for other things than payloads (e.g., parameters), that's why they're kept separated and strictly Schema objects. Our aim is to support multiple types of message payloads but not to support these types of schemas on any place of the spec.
