### ISSUE TITLE
[FEATURE REQUEST] Custom bindings within the software documentation.

### ISSUE THREAD

**Issue by prdatur** [asyncapi/asyncapi#297]
**Is your feature request related to a problem? Please describe.**
My problem is, we use for Websockets socket.io in some places. I checked the WS bindings, but this will not fit my needs. Because socket.io has channels to join.

**Can't it be tackled using specification extensions?**
It could be done in an extension.

**Describe the solution you'd like**
It would be nice, if we can document within the specification a binding type. I will provide an example for the existing websocket binding.

```
bindings:
  ws:
    description: This document defines how to describe WebSockets-specific information on AsyncAPI.
    version: Current version is 0.1.0.
    server:
      description: This object MUST NOT contain any properties. Its name is reserved for future use.
    channel:
      description: When using WebSockets, the channel represents the connection. Unlike other protocols that support multiple virtual channels (topics, routing keys, etc.) per connection, WebSockets doesn't support virtual channels or, put it another way, there's only one channel and its characteristics are strongly related to the protocol used for the handshake, i.e., HTTP.
      fields:
        method:
          type: string
          description: The HTTP method to use when establishing the connection. Its value MUST be either GET or POST.
        query:
          $ref: https://www.asyncapi.com/docs/specifications/2.0.0/#schemaObject
          description: A Schema object containing the definitions for each query parameter. This schema MUST be of type object and have a properties key.
        headers:
          $ref: https://www.asyncapi.com/docs/specifications/2.0.0/#schemaObject
          description: A Schema object containing the definitions of the HTTP headers to use when establishing the connection. This schema MUST be of type object and have a properties key.
        bindingVersion:
          type: string
          description: The version of this binding. If omitted, "latest" MUST be assumed.
    operation:
      description: This object MUST NOT contain any properties. Its name is reserved for future use.
    message:
      description: This object MUST NOT contain any properties. Its name is reserved for future use.
      
``'

**Comment by fmvilas** [comment]
Hi @prdatur. I'm confused here. Socket.io is not a protocol, it's a library/framework that lets you connect using WebSockets. The `bindings` are protocol bindings so you should be able to use Socket.io and the WS binding together. What's missing there in your opinion?

**Comment by prdatur** [comment]
As described in the WS binding. It will not be used with channels and topics, only one channel per connection.
But socket.io has channels, and operations and also messages (publish/subscribe) are used.
So for my understanding the binding with WS will only cover the connection it self.

Do we then just use publish/subscribe definition within the schema and add an additional "ws binding" or and that is the part I would then miss, do we have to bind the "type" first and then use the feature set what the binding will provide us?

Good example is the amqp. There you have all the information you need for amqp. exchange options, queue options and so on. 

After some time to think, I might agree with you If we just define the channel : publish / subscribe info's and then only bind the ws information to this.

Only the information that IT IS socket.io is missing. Is there any place to define "this connection is a socket.io connection"?

**Comment by fmvilas** [comment]
Having a way to tell the code generator that it should use Socket.IO is an implementation detail and not a protocol detail itself. Bindings are meant for protocol details and Socket.IO is not a protocol.

For instance, this example is perfectly valid:

```yaml
servers:
  production:
    url: myserver.com
    protocol: ws
channels:
  /first-channel:
    ...
  /second-channel:
    ...
```

You can then have a Socket.IO template on the [generator](https://github.com/asyncapi/generator) or another code generation software, and it will treat each channel as a Socket.IO channel. If what you want to do is to have a way to reuse our [Node.js WS](https://github.com/asyncapi/generator/tree/master/templates/nodejs-ws) template, then you could implement a template parameter there that will hint the code generator that it should use Socket.IO instead of plain WebSockets. For instance, you'll generate code like this:

```
ag asyncapi.yaml nodejs-ws -p framework=socketio
```

If instead, you put these details as part of the AsyncAPI file, then you're coupling implementation with API. Your AsyncAPI file should remain as independent as possible of the programming language that you'll use to implement it.

I'm closing this issue but feel free to reopen it if what I said doesn't make sense to you. Thanks!
