### ISSUE TITLE
[2.0.0 REVIEW] Regarding forcing a naming convention

### ISSUE THREAD

**Issue by basickarl** [asyncapi/asyncapi#308]
It's a rather quick question: *Does* the 2.0.0 specification today force a specific *naming convention*?

From reading the documentation it seems that `camel case` has been forced onto it due to the following parts of the specification: https://www.asyncapi.com/docs/specifications/2.0.0/#a-name-messageobject-a-message-object

All of the fixed fields are `camel case` leading me to believe that `camel case` is indeed the choice of naming convention for the specification. I however don't see in the specification that this is clearly written? 

Would it be a good idea to have this stated? Currently it seems that mixing naming conventions is allowed to happen.

Why would we want to force a naming convention? Look at HTTP headers, they are set in stone. It would be beneficial if everyone would follow the same standards.

**Comment by fmvilas** [comment]
First of all, thanks for being patient on this 🙏 

In my opinion, we shouldn't enforce this at spec level. The folks @stoplightio are working on adding support for AsyncAPI on their linter, [Spectral](https://www.github.com/stoplightio/spectral/). This will allow anyone to configure the naming convention they'd like.

> Why would we want to force a naming convention? Look at HTTP headers, they are set in stone. It would be beneficial if everyone would follow the same standards.

They're not, AFAIK. They might recommend using one convention but nothing prevents you from sending `my_custom_header` or `my-custom-header`. In any case, HTTP is a runtime protocol and it'd make sense if they do it, because it could affect interchangeability.

**Comment by basickarl** [comment]
@fmvilas Ah I apologize, I was meaning generally in specifications it's normally set to the same (a common standard). Of course one can use other formats n header fields!

**Comment by fmvilas** [comment]
So you mean following a naming convention inside the spec document?
