### ISSUE TITLE
AMQP Message Exchange

### ISSUE THREAD

**Issue by gmr** [asyncapi/asyncapi#41]
I noticed there is no construct for an exchange in AMQP. It would be nice to have that explicitly called out somehow.

**Comment by fmvilas** [comment]
Must confess that I thought about it but rejected the idea of including it since it's not part of the AMQP protocol spec (is it?) and it's not something common in messaging systems. I would suggest you use [specification extensions](https://github.com/asyncapi/asyncapi#specificationExtensions) for that purpose. Example:

```yaml
x-exchange: my-exchange
```

And then, it could be part of docs and code generators (and other software) **only** if the protocol is `amqp`.

**Comment by fmvilas** [comment]
We could use the feature suggested in #42 to solve this problem.

**Comment by fmvilas** [comment]
This will be addressed in version 2 because it's a breaking change.
