### ISSUE TITLE
Spec updated in the same branch: Bindings used to be a free-form map

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/asyncapi#412]
Issue part of #397

this is no longer the case, what about unknown protocols? We are supporting known protocols and unknown protocols as free form nodes, now unknown protocols are no longer supported.

**Comment by fmvilas** [comment]
Updating the spec in the same branch is not my favorite thing either. It's very confusing. However, it's still a correct and valid approach. If you want to know which is the stable version, you should browse files on the `2.0.0` tag: https://github.com/asyncapi/asyncapi/tree/2.0.0.

Regarding bindings, it was never a free-form map AFAIK. Where did you see that? "Unknown" protocols can still be supported using spec extensions. Also, feel free to add more protocols to the list as @dunglas did with Mercure [here](https://github.com/asyncapi/asyncapi/pull/278) and [here](https://github.com/asyncapi/bindings/pull/17).

**Comment by gutee** [comment]
Hi @fmvilas, we are seeing the 2.0.0 tag as we need a stable version of the API to have full support. So in that version we see the bindings field defined as "A free-form map where the keys describe the name of the protocol and the values describe protocol-specific definitions for the server." and spec extensions were not supported at bindings level in that version. So that free-form map tells us that there are defined protocols and you can add "unknown" protocols to the map, as it is free-form and can't be extended.

I understand that later on the spec extensions were added and the "free-form map" sentence was changes to just Map, but the 2.0.0 stable tag does't have that, that is why we support the free-form map.

**Comment by fmvilas** [comment]
Yeah, that was actually a mistake and never intended to be like that. I'd recommend you don't support a free-form map there and instead add "unknowns" as extensions, like `x-my-unknown-binding`.
