### ISSUE TITLE
[BUG] Inconsistencies in AsyncApi 2.0.0 examples

### ISSUE THREAD

**Issue by char0n** [asyncapi/asyncapi#437]
**Describe the bug**

I've found an inconsistencies in [AsyncAPI 2.0.0 specification document](https://www.asyncapi.com/docs/specifications/2.0.0/). The problem can be seen in [Servers Object](https://www.asyncapi.com/docs/specifications/2.0.0/#serversObject). Servers Object is defined as Patterned Field object. Later in the documentation there is an example of Servers Object which defines it as an array.

**To Reproduce**
1. Open https://www.asyncapi.com/docs/specifications/2.0.0/#serversObject
2. Scroll down to see example
```json
{
  "servers": [
    {
      "url": "{username}.gigantic-server.com:{port}/{basePath}",
      "description": "The production API server",
      "protocol": "secure-mqtt",
      "variables": {
        "username": {
          "default": "demo",
          "description": "This value is assigned by the service provider, in this example `gigantic-server.com`"
        },
        "port": {
          "enum": [
            "8883",
            "8884"
          ],
          "default": "8883"
        },
        "basePath": {
          "default": "v2"
        }
      }
    }
  ]
}
```

**Expected behavior**

Definition of Servers Objects vs example is incorrect (object vs array).

**Comment by fmvilas** [comment]
Hi @char0n! Thanks for opening the issue. This is a known problem between our website docs and the source of truth which is on Github here: https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#serversObject.

It's already fixed there but we didn't push to the website because we haven't released a new version yet.

Thanks a lot! 🙏
