### ISSUE TITLE
Add support for server.scheme 'jms'

### ISSUE THREAD

**Issue by wout3r** [asyncapi/asyncapi#52]
Hi,

We would like to use AsyncAPI to describe asynchronous messaging services that are exposed over JMS
and would therefor like to be able to specify 'jms' as a value for server.scheme. 

Protocol-specific message details, as proposed in #42 , are initially not required. Mapping from an AsyncAPI description to JMS constructs by convention already brings us pretty far.

Thanks in advance for considering this feature!

**Comment by fmvilas** [comment]
Hey @wout3r, sure thing. If you have the time I'd appreciate a PR. It should be fairly easy, just update [this](https://github.com/asyncapi/asyncapi/blob/develop/schema/asyncapi.json#L188) and [this](https://github.com/asyncapi/asyncapi/blob/develop/README.md#fixed-fields-4).

Otherwise, I'll add it during the week.

Thanks for the feedback!
