### ISSUE TITLE
How would client code look like?

### ISSUE THREAD

**Issue by bali182** [asyncapi/asyncapi#98]
Hello guys, great props for trying to standardise this! I might have missed it, but I only found examples for node-js server side code generation. How would the client code look like? 

```
const ws = new WebSocket('...', '...')

ws.send(JSON.stringify({ /* what goes here */ }))

ws.onmessage = (ev) => {
  ev.data // what is this?
}
```

In other words, where would the payload, and the topic go for a message?

**Comment by fmvilas** [comment]
Hey @bali182! You just spotted an unsupported feature in the current tooling. In AsyncAPI 1.2.0, we added support for Events APIs, a terrible name for APIs that don't have topics, just a single channel like WebSockets. That said, if you create a code generator for a consumer, and want to use WebSockets, it should read from the `events` section instead of the `topics` one.

```js
const ws = new WebSocket('...', '...')

ws.send(JSON.stringify({
	/* 
	Here comes the data you want to publish. You can validate its correctness against the payload defined under `events[].send`.
	*/
}))

ws.onmessage = (ev) => {
  ev.data // Here you receive the data from a WebSockets server. You can validate its correctness against the payload defined under `events[].receive`.
}
```

Hope it clarifies things a bit.

**Comment by bali182** [comment]
Hi @fmvilas, thanks for getting back to me! What I meant to ask is that to my knowledge Websockets don't support channels (I might be wrong on this I just started exploring the subject). I assumed that topics and possible other metadata were part of the payload (data field in the event) JSON encoded, or some other format.

What I basically mean is let's say we are working with this (`lightMeasured` schema is irrelevant for the question):
```
topics:
  event.{streetlightId}.lighting.measured:
    publish:
      $ref: '#/components/messages/lightMeasured'
```
If I understand correctly this is something that the socket client would listen to in `onmessage`. How would I detect from the data available that we hit this specific topic/route? Also how would I extract the actual payload (object matching `lightMeasured` schema)?

**Comment by bali182** [comment]
The reason I'm asking this is because I'm interested in writing a client side code generator for this, but first I'd like to understand the internals, and how chanels, payloads, possibly other metadata, etc... is transported if I have nothing but a pure WebSocket.

**Comment by fmvilas** [comment]
This is a Socket.io implementation detail. If you really want to use AsyncAPI with WebSockets, you can't use the `topics` section of the spec. Instead, use the `events` section. Check out this Slack Events API example: https://github.com/asyncapi/asyncapi/blob/master/test/docs/slack-rtm.yml#L14.

Notice how I don't specify topics because WebSockets don't have the concept of topics. There's only one channel when using WebSockets.

Does it make sense?

**Comment by bali182** [comment]
@fmvilas Yes definitely! This format is super clean.
